default:
  image: $CI_REGISTRY_IMAGE/builder

stages:
- prep
- build
- test

.TEMPLATE-prep-docker:
  stage: prep
  image: docker:dind
  services:
    - name: docker:dind

  script:
  - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD  
  - docker pull $CI_REGISTRY_IMAGE/$IMAGE:latest || echo Not built yet
  - docker build -t $CI_REGISTRY_IMAGE/$IMAGE -f $IMAGE.dockerfile --cache-from $CI_REGISTRY_IMAGE/$IMAGE:latest .
  - docker push $CI_REGISTRY_IMAGE/$IMAGE

prepare builder image:
  extends:
  - .TEMPLATE-prep-docker
  variables:
    IMAGE: builder
  only:
    changes:
    - builder.dockerfile

prepare integration image:
  extends:
  - .TEMPLATE-prep-docker
  variables:
    IMAGE: integration
  only:
    changes:
    - integration.dockerfile

build:
  stage: build
  script:
  - make
  artifacts:
    paths:
    - bin
    expire_in: 1 hour

test:
  stage: test
  script:
  - make test

